#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse

from Bio import SeqIO
from BioSQL import BioSeqDatabase
from BioSQL.BioSeq import DBSeq
from seqann import BioSeqAnn, gfe
from seqann.blast_cmd import get_locus
import time


def main():
    """This is run if file is directly executed, but not if imported as
    module. Having this in a separate function  allows importing the file
    into interactive python, and still able to execute the
    function for testing"""
    parser = argparse.ArgumentParser()
    parser.add_argument("-f", "--file",
                        required=True,
                        help="input file",
                        type=str)

    parser.add_argument("-l", "--locus",
                        required=False,
                        help="HLA locus",
                        type=str)

    parser.add_argument("-o", "--output",
                        required=True,
                        help="Output file where GFE will be stored",
                        type=str)    

    parser.add_argument("-k", "--kir",
                        required=False,
                        help="Bool for KIR",
                        action='store_true')

    parser.add_argument("-s", "--server",
                        required=False,
                        help="BioSQL server",
                        default=False,
                        type=bool)

    parser.add_argument("-v", "--verbose",
                        help="Option for running in verbose",
                        action='store_true')

    args = parser.parse_args()
    fastafile = args.file
    loc = args.locus
    serv = args.server
    output_filename = args.output

    verbose = False
    if args.verbose:
        verbose = True

    kir = False
    if args.kir:
        kir = True

    server = None
    if serv:
        server = BioSeqDatabase.open_database(driver="pymysql", user="root",
                                              passwd="", host="localhost",
                                              db="bioseqdb")

    seqann = BioSeqAnn(verbose=verbose, server=server, kir=kir)

    id_spacer = '{:*^20}'.format("")
    f_out = open(output_filename, 'a+')
    f_out.seek(0)
    ids = []
    for line in f_out:
        if id_spacer in line:
            spacer1, id, spacer2 = line.split(' ')
            ids.append(id)
    num_existing_ids = len(ids)
    if num_existing_ids:
        print(num_existing_ids, "rows in existing output")

    gfe_maker = gfe.GFE()
    start_time_rel = start_time_abs = time.time()
    n = 0
    for seq in SeqIO.parse(fastafile, "fasta"):
        try:
            if seq._seq and seq.description not in ids:
                if not loc:
                    loc = get_locus(seq, kir=kir, verbose=verbose,
                                    refdata=seqann.refdata)

                try:
                    ann = seqann.annotate(seq, loc)
                except ValueError as e:
                    print("Skipping sequence: " + loc + " reason:", e)
                    break

                features, gfe_name = gfe_maker.get_gfe(ann, loc)
                f_out.write('{} {:^20} {}\n'.format(id_spacer, str(seq.description), id_spacer))
                l = 0
                for f in ann.annotation:
                    f_seq = ann.annotation[f] if isinstance(ann.annotation[f], DBSeq) else ann.annotation[f].seq
                    f_out.write('\t'.join([gfe_name, f, ann.method, str(f_seq)]) + '\n')
                    l += len(f_seq)
                f_out.write('\n')
                if n and n > num_existing_ids and n % 1 == 0:
                    print('%s rows loaded after %.2f seconds (with a length of %s)' %
                            (n - num_existing_ids, time.time() - start_time_rel,
                            len(seq)))
                    start_time_rel = time.time()
                n += 1
        except Exception as e:
            print("Error with %s at index %s: %s" % (seq.description, n, e))
    
    print(i, "total rows loaded")

    if serv:
        server.close()


if __name__ == '__main__':
    """The following will be run if file is executed directly,
    but not if imported as a module"""
    main()
